### ISSUE TITLE
how to use schema in Cocos Creator client?

### ISSUE THREAD

**Issue by bytetalking** [colyseus/cocos-demo-tictactoe#1]
hello, this project looks has no Schema class defined in client scripts, only work with any?

**Comment by endel** [comment]
there are two ways to use strongly typed schemas classes on the client-side in TypeScript:

## Importing the type
You can use `import type` to import only the type from the backend folder directly: 

```typescript
import type { YourState } from "../your-server/schemas/YourState.ts
```

And later provide `YourState` to the matchmaking method:

```typescript
const room = await client.joinOrCreate<YourState>("my_room");
room.state // auto-completes
```

## Providing the concrete schema implementation

You can import the concrete schema implementation (either directly from the server, or re-generated specially for the client-side through `schema-codegen`)

```typescript
import { YourState } from "../shared-schemas/YourState.ts
```

And later provide `YourState` as third argument for the matchmaking method:

```typescript
const room = await client.joinOrCreate("my_room", {}, YourState);
room.state // auto-completes
```

---

Hope this helps! Cheers!
